services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: tiny_rest_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: userPassword
    expose:
      - "5432:5432"